### ISSUE TITLE
Applying Recall effect through commands does not work

### ISSUE THREAD

**Issue by Mickeon** [ViniciusIth/gohome-mod#5]
Hello. We've been using this mod as part of a private friend modpack. There's currently a relatively simple oddity: When giving this through any other means than normal (such as by other mods or commands) the teleport will not trigger.
To reproduce the issue, write `/effect give @s gohome:recall` in the chat.

**Comment by ViniciusIth** [comment]
I think I know what might be causing the error. I'll try to fix it as soon as possible.

**Comment by ViniciusIth** [comment]
Fixed on [version 1.3.1](https://modrinth.com/mod/go-home/version/1.3.1). Thank you!
